### ISSUE TITLE
Multi jira project support

### ISSUE THREAD

**Issue by albertaouad** [b-yond-infinite-network/ga-sync-issues-to-jira#11]
A repository can be used in multiple Jira projects.
Currently JIRA_PROJECTKEY supports one value only.
Extend to support a List and add validation to pick the right project based on the label used.

> e.g. JIRA_PROJECTKEY: [INT, SDAA]
>        INT-466 use project INT
>        SDAA-234 use project SDA

**Comment by bruno-morel** [comment]
Added in build [0.5.0](https://github.com/b-yond-infinite-network/ga-sync-issues-to-jira/releases/tag/v0.5.0)
