### ISSUE TITLE
To be able to create JIRA ticket from Github issues

### ISSUE THREAD

**Issue by nicopadu** [b-yond-infinite-network/ga-sync-issues-to-jira#14]
Current implementation works around a label in Github issue that links uniquely to an existing JIRA Ticket. For this to work, we need to have previously created JIRA tickets.

It would be really nice to have a special label key (i.e: 'CREATE-JIRA') that when added to Github issue, it creates a new JIRA ticket. 
By creating a new JIRA ticket it would mean:
* This approach would not be compatible with SUBTASK_MODE
* Type of JIRA ticket should be form configuration
* After creating a new JIRA ticket, action receives the new jira key, it would need to update Github issue to replace our special label ('CREATE-JIRA') but the new jira key obtained. Then subsequent updates will kept in sync

Probably there are some other limitations around JIRA that I'm not aware of. But it would be nice to have such option available for cases that we directly create Github issues and we don't want to group multiple of them under a single "previously created" JIRA ticket

**Comment by bruno-morel** [comment]
Great idea. That's easily doable. I would advise that we still force an attachement to an Epic by default...and only give an obscure setting to allow this completely..
Opening it up to "everything that's tagged CREATE-JIRA gets create in JIRA" can quickly get messy inside JIRA...So it would be better to allow only power users to do it....

Agreed?

**Comment by bruno-morel** [comment]
You and @albertaouad should be happy to know that it does exactly that in version 0.6.3.
You will have to configure the GITHUB_TOKEN (it's in the README :P) and make sure you have a JIRA_DEFAULT_PARENT or JIRA_DEFAULT_EPIC (depending if you're in Subtask mode or not)

Let me know if that covers it...
